name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Check Python Version
        run: python --version